"""utils"""

SYSTEM_PROMPT = """You're a data analyst, tasked with analyzing whether certain
career milestones pertain based upon a biography you're given. I will give you
a biography, a list of JSON keys, and a brief description for each key. Your
job will be to read through the biography, then, for each JSON key, return
either the part of the biography that makes you think that key pertains or the
boolean `false`. If there's more than one part of the biography that makes you
think the key pertains, return only the first part of the biography that makes
you think the key pertains.

For example, with JSON keys
    ['communityCollege', 'eliteCollege', 'publicCollege', 'privateCollege', 'noBA']
and a biography that starts:
    "a Representative from Missouri; born in Baytown, Harris County, Tex., October 4, 1963; graduated from Ross S. Sterling High School, Baytown, Tex., 1982; attended Lee College, Baytown, Tex.; attended Southwest Texas State College, San Marcos, Tex.; attended University of Texas, Austin, Tex.; television news anchor;..."

Your response should be as follows:
{
    "communityCollege": "Lee College, Baytown, Tex.",
    "eliteCollege": false,
    "publicCollege": "attended Southwest Texas State College, San Marcos, Tex.",
    "privateCollege": false,
    "noBA": false
}
"""

KEYS_AND_EXPLANATIONS = """
    'communityCollege', # does this person have an associates degree and/or attend a community college?
    'eliteCollege', # did this person complete their UNDERGRAD education at an Ivy League School, Stanford, UChicago, Duke, or MIT? say False if it's a grad degree
    'publicCollege', # undergrad at public school
    'privateCollege', # ud
    'noBA', # no bachelors degree
    'lawSchool', # JD, LLM, or any other law degree
    'medDegree', # include DOs and nursing degrees, too
    'doctorate',
    'mba',
    'otherMasters',
    'military',
    'lawyerPrivatePractice',
    'publicLawyerOrJudge',
    'prevUnsuccessfulCandidate',
    'partyPolitics', # did they ever work for the local/state/national branch of Democratic/Republican/third party? don't include "elected as a Democrat" or "elected as a Republican"
    'sciOrEng', # ever have a job
    'religion',
    'healthcare',
    'blueCollarOrServiceJob',
    'education', # only include people who were teachers / professors / administrators
    'nonprofitsAndUnions',
    'sports', # both players and coaches
    'media',
    'realEstate',
    'lawEnforcement',
    'farmingOrRanching',
    'businessOrManagement',
    'lobbyingOrPacs',
    'localGov',
    'stateLeg',
    'electedFedOrStateOffice', # don't include being in the state legislature, DO NOT include being elected to congress. CA high speed rail authority isn't elected.
    'nonElectedGovJob' # everything from staffer/aide in a legislature to being an appointed official
"""

state_list = [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Hawai'i",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "West Virginia",  # putting WV before VA so that WVs don't get mislabeled as VAs
    "Virginia",
    "Washington",
    "Wisconsin",
    "Wyoming",
]

state_dict = {
    "Alabama": "AL",
    "Montana": "MT",
    "Alaska": "AK",
    "Nebraska": "NE",
    "Arizona": "AZ",
    "Nevada": "NV",
    "Arkansas": "AR",
    "New Hampshire": "NH",
    "California": "CA",
    "New Jersey": "NJ",
    "Colorado": "CO",
    "New Mexico": "NM",
    "Connecticut": "CT",
    "New York": "NY",
    "Delaware": "DE",
    "North Carolina": "NC",
    "Florida": "FL",
    "North Dakota": "ND",
    "Georgia": "GA",
    "Ohio": "OH",
    "Hawaii": "HI",
    "Hawai'i": "HI",
    "Oklahoma": "OK",
    "Idaho": "ID",
    "Oregon": "OR",
    "Illinois": "IL",
    "Pennsylvania": "PA",
    "Indiana": "IN",
    "Rhode Island": "RI",
    "Iowa": "IA",
    "South Carolina": "SC",
    "Kansas": "KS",
    "South Dakota": "SD",
    "Kentucky": "KY",
    "Tennessee": "TN",
    "Louisiana": "LA",
    "Texas": "TX",
    "Maine": "ME",
    "Utah": "UT",
    "Maryland": "MD",
    "Vermont": "VT",
    "Massachusetts": "MA",
    "Virginia": "VA",
    "Michigan": "MI",
    "Washington": "WA",
    "Minnesota": "MN",
    "West Virginia": "WV",
    "Mississippi": "MS",
    "Wisconsin": "WI",
    "Missouri": "MO",
    "Wyoming": "WY",
}

number_of_reps = {
    "Alabama": 7,
    "Alaska": 1,
    "Arizona": 9,
    "Arkansas": 4,
    "California": 52,
    "Colorado": 8,
    "Connecticut": 5,
    "Delaware": 1,
    "Florida": 28,
    "Georgia": 14,
    "Hawaii": 2,
    "Idaho": 2,
    "Illinois": 17,
    "Indiana": 9,
    "Iowa": 4,
    "Kansas": 4,
    "Kentucky": 6,
    "Louisiana": 6,
    "Maine": 2,
    "Maryland": 8,
    "Massachusetts": 9,
    "Michigan": 13,
    "Minnesota": 8,
    "Mississippi": 4,
    "Missouri": 8,
    "Montana": 2,
    "Nebraska": 3,
    "Nevada": 4,
    "New Hampshire": 2,
    "New Jersey": 12,
    "New Mexico": 3,
    "New York": 26,
    "North Carolina": 14,
    "North Dakota": 1,
    "Ohio": 15,
    "Oklahoma": 5,
    "Oregon": 6,
    "Pennsylvania": 17,
    "Rhode Island": 2,
    "South Carolina": 7,
    "South Dakota": 1,
    "Tennessee": 9,
    "Texas": 38,
    "Utah": 4,
    "Vermont": 1,
    "Virginia": 11,
    "Washington": 10,
    "West Virginia": 2,
    "Wisconsin": 8,
    "Wyoming": 1,
}

communityCollege = [
    "Lee College",
    "A.A.",
    "Community College",
    "Cerritos College",
    "Chesapeake College",
    "Texas Southmost College",
    "Junior College",
    "South Plains College",
    "Baltimore City College",
    "College of the Sequoias",
    "Camden County College",
    "Bakersfield College",
    "A.S., Indiana University South Bend, South Bend, Ind.",
]

eliteCollege = [
    "Massachusetts Institute of Technology",
    "University of Pennsylvania",
    "Cornell University",
    "Dartmouth",
    "Princeton",
    "Yale",
    "Duke",
    "University of Chicago",
    "Brown",
    "Stanford University",
    "Columbia University",
    "Harvard",
]

publicCollege = set(
    [
        "United States Naval Academy",
        "Western Kentucky University",
        "Jackson State University",
        "University of South Florida",
        "Oregon State University",
        "University of South Dakota",
        "University of Colorado, Boulder",
        "Harris-Stowe State University",
        "University of Arizona",
        "Cleveland State University",
        "University of Mississippi",
        "University of Wisconsin",
        "University of Arkansas",
        "University of Georgia",
        "St. Cloud State University",
        "Prairie View A&M University",
        "Prairie View A",
        "University of Arizona, Tucson",
        "University of North Carolina",
        "University of Houston",
        "Texas Tech University",
        "Ball State University",
        "Northeastern Illinois University",
        "University of California, Santa Barbara",
        "Missouri State University",
        "University of Southern Mississippi",
        "University of Wyoming",
        "Lincoln University",
        "University of Maryland",
        "Buffalo State College,",
        "University of Puerto Rico",
        "University of California, Los Angeles",
        "University of Florida",
        "Washington State University",
        "Ohio University",
        "Georgia State University",
        "Athens State University",
        "Southern Connecticut State University",
        "University of Southern Mississippi",
        "Utah State University",
        "University of California, Los Angeles",
        "United States Air Force Academy, Colorado Springs",
        "Oklahoma State University",
        "University of Missouri",
        "University of Nevada",
        "Lamar University",
        "Morgan State University",
        "University of Hawaii",
        "University of Guam",
        "University of California, Irvine",
        "North Texas State University",
        "University of South Dakota",
        "University of Michigan",
        "University of Wisconsin, Oshkosh",
        "University of Kansas",
        "University of Texas, Austin",
        "Queens College",
        "University of Arizona",
        "Kent State University",
        "Pittsburg State University",
        "Wayne State University",
        "University of Guam",
        "United States Military Academy",
        "University of Michigan",
        "United States Military Academy",
        "West Virginia University,",
        "Auburn University",
        "Texas Tech University",
        "University of California, Berkeley",
        "The Citadel, The Military College of South Carolina,",
        "University of Puerto Rico",
        "University of Missouri",
        "University of West Florida",
        "Arizona State University",
        "Mississippi State University",
        "United States Military Academy",
        "Lake Superior State University",
        "Ohio State University",
        "East Tennessee State University",
        "Jacksonville State University",
        "Ohio State University",
        "United States Military Academy",
        "University of Illinois, Urbana-Champaign",
        "Virginia State University",
        "University of Nevada",
        "Ohio State University",
        "Texas Tech University",
        "Louisiana State University",
        "University of Texas, Austin",
        "California State University, Long Beach",
        "United States Military Academy",
        "University of Wisconsin, Madison",
        "University of North Carolina, Chapel Hill",
        "Michigan State University",
        "New Mexico State University",
        "University of San Francisco",
        "Southern Arkansas University",
        "University of Virginia",
        "California State University, Fresno",
        "University of California, Los Angele",
        "Kansas State University",
        "Northern Illinois University",
        "University of Memphis",
        "Central Michigan University",
        "University of Maryland",
        "University of California, Santa Barbara",
        "California State University, Los Angeles",
        "Purdue University",
        "Eastern Oregon State College",
        "California Polytechnic State University, San Luis Obispo",
        "University of Florida, Gainesville",
        "University of North Carolina, Chapel Hill",
        "Florida Agricultural and Mechanical University",
        "Georgia Institute of Technology",
        "Metropolitan State University of Denver",
        "Oklahoma State University",
        "Pennsylvania State University Behrend College",
        "University of Oregon",
        "University of Florida, Gainesville",
        "University of Georgia",
        "Morehouse Colleg",
        "Central State University",
        "University of Utah",
        "Auburn University",
        "Shippensburg State College",
        "University of South Carolina",
        "University of Georgia",
        "University of Northern Colorado",
        "University of Florida, Gainesville",
        "United States Air Force Academy",
        "Karnatak University, Dharwad, India",
        "Pennsylvania State University, University Park",
        "SUNY Geneseo",
        "University of Oregon",
        "South Dakota State University",
        "North Dakota State University",
        "University of Virginia",
        "University of Northern Iowa",
        "University of Wisconsin, Madison",
        "National University of Economics, Kyiv",
        "Texas Agricultural and Mechanical University",
        "University of North Carolina, Charlotte",
        "United States Naval Academy",
        "University of Maryland, College Park",
        "University of North Carolina, Chapel Hill",
        "Arkansas Tech University",
        "Arkansas A.M.&N. College",
        "Arkansas A.M.",
        "Binghamton University",
        "University of California, Berkeley",
        "Northern Illinois University",
        "Florida State University",
        "University of Arkansas",
        "University of California, Berkeley",
        "University of California, Berkeley",
        "University of Texas, San Antonio",
        "University of California, Los Angeles",
        "University of Illinois, Urbana-Champaign",
        "United States Military Academy",
        "University of Maryland, College Park",
        "University of Minnesota",
        "Truman State University",
        "Indiana University, Bloomington",
        "University of Washington",
        "University of Nebraska",
        "University of Minnesota",
        "United States Naval Academy",
        "University of Wisconsin, Madison",
        "University of Nevada",
        "University of Tennessee",
        "University of Missouri",
        "North Carolina Agricultural and Technical State University",
        "University of Florida",
        "University of Missouri",
        "Eastern Illinois University",
        "United States Naval Academy",
        "University of Wisconsin, River Falls",
        "University of Missouri",
        "United States Merchant Marine Academy",
        "Louisiana State University",
        "Tennessee Tech University",
        "Virginia Polytechnic Institute",
        "University of Wisconsin, Madison",
        "San Diego State University",
        "United States Naval Academy",
        "Oklahoma State University",
        "Indiana University, Bloomington",
        "University of Pittsburgh",
        "Florida State University",
        "University of Louisiana",
        "North Carolina Agricultural and Technical University",
        "Appalachian State University",
        "University of Louisville",
        "Arkansas State University",
        "Pennsylvania State University",
        "Ohio State University",
        "United States Naval Academy",
        "University of Wyoming, Laramie",
        "University of California, Davis",
        "University of Alaska, Fairbanks",
        "Virginia Military Institute",
        "Pennsylvania State University",
        "University of South Carolina",
        "University of Nebraska",
        "Rutgers University",
        "University of Missouri",
        "Louisiana State University",
        "Louisiana State University",
        "California State University",
        "Utah State University",
        "Arkansas Tech University",
        "University of California, Los Angeles",
        "University of California, Berkeley",
        "University of Hawaii",
        "United States Military Academy",
        "Tennessee Technological University",
        "University of Texas, Austin",
        "University of Illinois, Chicago",
        "University of Alabama",
        "Rutgers College",
        "University of Wisconsin, Milwaukee",
        "California State University, Fullerton",
        "University of California, Los Angeles",
        "Montana State University",
        "North Carolina State University",
        "Florida State University, Tallahassee",
        "Middle Tennessee State University",
        "Washington State University",
        "University of North Dakota",
        "University of Cincinnati",
        "University of Houston-Clear Lake",
        "University of Illinois, Urbana-Champaign",
        "University of Wisconsin, Madison",
        "University of Mississippi",
        "University of Maryland University College",
        "United States Naval Academy",
        "University of Virginia",
        "California State University, Chico",
        "University of Illinois, Urbana-Champaign",
        "United States Military Academy",
        "University of California",
        "University of Texas at El Paso",
        "Boise State University",
        "University of Kentucky",
        "Mississippi State University",
        "Metropolitan State University of Denver",
        "University of Missouri-Kansas City",
        "Pennsylvania State University, University Park",
        "California State University, Bakersfield",
        "Indiana University South Bend",
        "University of Missouri",
        "Clemson University",
        "University of Minnesota",
        "University of Memphis",
        "South Carolina State University",
        "Trenton State College",
        "University of Virginia",
        "University of Alabama",
        "San Diego State University",
        "University of Georgia",
        "University of Wisconsin, Madison",
        "University of Wisconsin",
        "Kansas State University",
        "Washington State University",
        "Iowa State University",
        "Thomas Edison State College",
        "University of Kansas",
        "Kean College",
        "Bowling Green State University",
        "New Mexico Highlands University",
        "Central Connecticut University",
        "M University",
    ]
)

privateCollege = set(
    [
        "University of Miami",
        "George Washington University",
        "Texas Wesleyan University",
        "Texas Wesleyan University",
        "Tougaloo College",
        "La Salle University",
        "Temple University",
        "Saint Mary's College of California",
        "Morehouse College",
        "Ohio Northern University",
        "Dordt College",
        "Bates College",
        "Marshall college",
        "Carnegie Mellon University",
        "Niagara University",
        "Gustavus Adolphus College",
        "American University",
        "Charleston Southern University",
        "Barry University",
        "College of the Holy Cross",
        "Trinity University",
        "National Labor College",
        "Texas Christian University",
        "Texas Christian University",
        "Xavier University",
        "Georgetown University",
        "College of the Atlantic",
        "Presbyterian College",
        "Reed College, Portland",
        "Calvin College",
        "Colorado College",
        "Colgate University",
        "Brigham Young University",
        "Wabash College",
        "Seton Hall University",
        "Belmont Abbey College",
        "Excelsior College",
        "University of Notre Dame",
        "Marquette University",
        "Adelphi University",
        "Clarkson University",
        "University of Southern California",
        "Harvard University Extension School",
        "Regis University",
        "Trinity College",
        "Wesleyan University",
        "Amherst College",
        "Emory University",
        "Wentworth Institute",
        "American University",
        "Vanderbilt University",
        "College of the Holy Cross",
        "Marymount College",
        "University of New Haven",
        "College of William and Mary",
        "George Washington University",
        "Northwood University",
        "California Institute of Technology",
        "Georgetown University",
        "Liberty University",
        "Fordham University",
        "Siena Heights College",
        "Pomona College",
        "Trinity University",
        "Roosevelt University",
        "University of Southern California",
        "Colgate University",
        "La Salle University",
        "Hope College",
        "Georgetown University",
        "College of Great Falls",
        "Johns Hopkins University",
        "Oral Roberts University",
        "Boston College",
        "Liberty University",
        "Saint Peter's College",
        "Tufts University",
        "Emory University",
        "Georgetown University",
        "Hamilton College",
        "Hofstra University",
        "Southwestern University",
        "Brigham Young University",
        "George Washington University",
        "Bethel College",
        "Grinnell College",
        "Notre Dame University",
        "Boston University",
        "Georgetown University",
        "Davidson College",
        "Vanderbilt University",
        "University of Redlands",
        "Washington & Lee University",
        "Tufts University",
        "Pepperdine University",
        "University of Notre Dame",
        "Loyola University",
        "Brigham Young University",
        "Boston University",
        "Baylor Universit",
        "Excelsior University",
        "Lewis and Clark College",
        "Georgetown University",
        "Fort Wayne Bible College",
        "Birmingham Southern College",
        "Cleary University",
        "University of Dayton",
        "Tulane University",
        "Fisk University",
        "Concordia University Wisconsin",
        "University of Richmond",
        "Pensacola Christian College",
        "Pacific Lutheran University",
        "Manhattan College",
        "Saint Lawrence University",
        "Washington and Lee University",
        "Lee University",
        "Boston University",
        "Middlebury College",
        "Wayland Baptist University",
        "Pepperdine University",
        "Embry-Riddle Aeronautical University",
        "Albright College",
        "George Washington University",
        "College of St. Catherine",
        "Marquette University",
        "Vanderbilt University",
        "Columbia College",
        "Georgetown University",
        "Creighton University",
        "American International Colleg",
        "Smith College",
        "Rhodes College",
        "Drake University",
        "Troy University",
        "Vanderbilt University",
        "Talladega College",
        "Georgetown University",
        "Miami University of Ohio",
        "Wesleyan University",
        "Bradley University",
        "Smith College",
        "Sam Houston State University",
        "Brigham Young University, Provo",
        "Brigham Young University, Provo",
        "Kenyon College",
        "Emmanuel College",
        "Concordia College",
        "Jacksonville University",
        "Brigham Young University",
        "Williams College",
        "Williams College",
        "American Military University",
        "Clark College (Clark Atlanta University)",
        "Mills College",
        "University of Miami",
        "Baylor University",
        "Williams College",
        "George Washington University",
        "Oberlin",
        "Mount Vernon College",
        "Georgetown University",
        "Missouri Valley College",
        "Maryknoll College",
        "Emory &  Henry College",
        "Loras College",
        "Texas Women's University",
        "American University",
        "Georgetown University",
        "Northwestern University",
        "Middlebury College",
        "Fairleigh Dickinson University",
        "College of the Holy Cross",
        "Swarthmore College",
        "Reed College",
        "Furman University",
        "Gordon College",
        "Biola University",
        "Alma College",
        "St. Lawrence University",
        "Antioch College",
        "Fordham University",
        "Howard University",
        "Boston College",
        "University of San Diego",
        "Henry College, Emory",
    ]
)

lawSchool = ["J.D."]

medDegree = [
    "RN Diploma",
    "D.D.S.",
    "M.S.N./M.P.H.",
    "M.D.",
    "D.P.M.",
    "Pharm.D",
]

doctorate = [
    "D.Phil.",
    "Ed.D.",
    "D.P.A.",
    "Ph.D.",
]

mba = ["M.B.A."]

otherMasters = [
    "M.F.",
    "M.E.M.",
    "M.A.C.T.",
    "M.Div.",
    "M.P.M.",
    "LLM,",  # not counting this as a law degree
    "S.M.",
    "M.A.R.",
    "M.H.S.",
    "M.F.A.",
    "M. Phil.",
    "M.P.P.M.",
    "M.I.A.",
    "M.A.L.D.",
    "M.P.H.",
    "M.Sc.",
    "Ed.M.",
    "M.S.",
    "M.P.P.",
    "M.S.W.",
    "M.P.A.",
    "M.A.",
    "M.I.L.R.",
    "M.Ed.",
]

military = [
    "U.S. Army",
    "United States Marine Corps",
    "United States Air Force",
    "National Guard",
    "United States Navy",
    "United States Army",
]

lawyerPrivatePractice = [
    "lawyer, private practice",
    "practiced law",
]

publicLawyerOrJudge = set(
    [
        "Illinois special assistant attorney general",
        "staff attorney, Wyoming state attorney general's office",
        "staff counsel",
        "clerk, U.S. Court of Appeals",
        "district court judge",
        "assistant commonwealth's attorney",
        "county judge",
        "assistant United States attorneysolicitor",
        "attorney general of Alaska",
        "senior attorney, Natural Resources Defense Council",
        "senior counselor to the chairman of the Federal Communications Commission",
        "attorney, Education Law Center of Pennsylvania",
        "legal counsel to Illinois Lieutenant Governor Paul Simon",
        "magisterial district judge",
        "attorney, United States Department of Justice",
        "lawyer, Federal Trade Commission",
        (
            "assistant attorney general, office of the Mass. state attorney general,"
            " 1987-1989"
        ),
        "counsel",
        "assistant district attorney",
        "special counsel",
        "counsel, U.S. Senate Subcommittee on Alcoholism and Narcotics",
        "municipal judge",
        "assistant Maryland state's attorney",
        "attorney general of Missouri",
        "deputy general counsel, United States Department of Energy",
        "staff, office of the attorney general, Calif. state department of justice",
        "attorney, Memphis Police Department",
        "city attorney",
        "public defender",
        "U.S. attorney",
        "worked as an attorney in the non-profit sector",
        "justice of the Texas state supreme court",
        "prosecuting attorney",
        "associate judge",
        "County attorney",
        "judicial law clerk",
        "United States attorney",
        "prosecutor",
        "director and presiding judge",
        "deputy attorney",
        "District Court attorney",
        "commonwealth attorney",
        "district attorney",
        "United States Attorney",
        "law clerk",
        "Judge",
    ]
)

prevUnsuccessfulCandidate = ["unsuccessful", "Unsuccessful"]

partyPolitics = ["party", "Party", "National Convention", "National Committee"]

sciOrEng = [
    "geologist",
    "chemist",
    "physicist",
    "computer software developer",
    "scientist",
    "engineer",
    "cybersecurity consultant",
    "computer programmer",
]

religion = [
    "religious leader",
    "pastor",
    "Baptist pastor",
    "lay minister",
    "minister",
]

healthcare = [
    "ophthalmologist",
    "nurse",
    "pediatrician",
    "pharmacist",
    "nurse",
    "surgeon",
    "urologist",
    "optometrist",
    "medicine",
    "internal medicine",
    "emergency medical technician",
    "pediatric",
    "medical doctor",
    "physician",
    "dentist",
]

blueCollarOrServiceJob = [
    "firefighter",
    "sales representative",
    "flight attendant",
    "restaurateur",
    "rideshare driver",
    "childcare specialist",
    "carpenter",
    "truck manager",
    "plumber",
    "hotel service employee",
]

education = [
    "member of the board of regents of the University of Colorado",
    "senior program development specialist, University of Arizona",
    "college counselor",
    "teaching assistant",
    "school administrator",
    "postdoctoral research",
    "member of the board of directors, Portland Community College",
    "dean",
    "elementary school principal",
    "ombudsperson",
    "Teach for America Corps",
    "research fellow",
    "faculty",
    "senior fellow, University of Massachusetts",
    "professor",
    "instructor",
    "teacher",
]

nonprofitsAndUnions = [
    "United Nurses Association of California",
    "executive director, Community Housing Developers",
    "National Association for the Advancement of Colored People",
    "Project Right Start",
    "AFL-CIO",
    "community organizer",
    "youth program director",
    "EMILY'S List",
    "volunteer",
    "CEO, Helping Hands Hawaii",
    "executive director, Westside Health Planning Organization",
    "United States Peace Corps",
    "Director of planning, National Center for Urban Ethnic Affairs",
    "non-profit",
    "union",
    "fellow, NAACP Legal Defense and Educational Fund",
    "director, South Dakota state municipal league",
    (
        "director, Charleston County, S.C., neighborhood youth corps and new careers"
        " projects"
    ),
    "nonprofit",
    "co-chair, San Francisco Education Fund's Permanent Fund 1988-1989",
    "American Civil Liberties Union",
]

sports = [
    "sports",
    "coach",
    "athlete",
    "baseball",
    "football",
]

media = [
    "anchor",
    "media owner",
    "political commentator",
    "writer",
    "newspaper editor",
    "columnist",
    "radio",
    "television program host and co-producer",
    "columnist",
    "author",
    "journalist",
    "newspaper publisher",
]

realEstate = [
    "mortgage",
    "Realtor",
    "realtor",
    "real estate",
]

lawEnforcement = [
    "Federal Bureau of Investigation",
    "parole officer",
    "postal inspector",
    "police",
    "sheriff",
    "emergency 9-1-1 dispatcher",
    "justice of the peace",
    "deputy probation officer",
]

farmingOrRanching = [
    "agriculture",
    "family orchard business",
    "farmer",
    "rancher",
]

businessOrManagement = set(
    [
        "accountant",
        "landscape nursery owner",
        "sales representative",
        "executive",
        "co-owner of telecommunications engineering firm",
        "insurance broker",
        "investment professional",
        "customer service representative",
        "media owner",
        "entrepreneur",
        "public relations consultant",
        "public relations professional",
        "automobile dealer",
        "financial analyst",
        "government analyst",
        "venture capitalist",
        "youth camp director",
        "healthcare company manager",
        "analyst",
        "co-founded the company that became Nextel",
        "stockbroker",
        "engaged in the oil industry",
        "energy conservation company owner",
        "marketing representative",
        "space exploration company owner",
        "insurance agency owner",
        "sales representative",
        "managing director, Anschutz Investment Co.",
        "cost engineer",
        "financial analyst",
        "consult",
        "certified public accountant",
        "financial advisor",
        "entrepreneur",
        "human resources professional",
        "insurance agent",
        "chief operating officer",
        "business",
        "accountant",
        "businessman",
        "vice president, UBS/Paine Webber",
        "CEO",
        "restaurant manager",
        "bank",
    ]
)

lobbyingOrActivism = [
    (
        "political campaign consultant and strategist;  political action committee"
        " executive"
    ),
    "lobbyist",
    "political consultant",
    "political action committee",
    "professional advocate",
    "private advocate",
]

localGov = [
    "zoning commission",
    "board of supervisors",
    "school board",
    "city council",
    "board of education",
    "Township",
    "mayor of",
    "staff, Santa Barbara County, Calif., supervisor Naomi Schwartz",
    "treasurer, Sioux County",
    "member of the St. Elizabeth, Mo., board of trustees",
    "common council",
    "Charleston County, S.C. council",
    "chief of the Miami, Fla. fire-rescue department",
    "Mayor of Snow Hill, N.C.",
    "chief of staff to Minneapolis mayor R.T. Rybak",
    "assistant county manager, Clark County, Nev.",
    "alderman",
    "aldermen",
    "Sacramento County, Calif., chief medical officer",
    "member of the North Haven (Maine) board of assessors",
    "administrative staff advisor, Summit County, Ohio, fiscal office",
    "county executive",
    "Maricopa County, Ariz., treasurer",
    "Concord Township, Ohio, trustee",
    "member of the Calhoun County, Ala., commission",
    "staff, New York, N.Y. council member Jimmy Vacca",
    "member of the West Lampeter, Pa., planning commission",
    "County commissioner",
    "staff, Mayor Frank Logue of New Haven, Conn.",
    "mayor of Burlington, Vt.",
    "member of the Marin County, Calif., municipal water district board of directors",
    "commissioner, Putnam County, Ind.",
    "board of commissioners",
    "Mecklenburg County, N.C., commissioner",
    "Montgomery County, Ohio, executive director, human services",
    "member, Monroe County legislature",
    "member of the Greenwich, Conn., housing authority",
    "town council",
    "member of the village of Amityville, N.Y., board of trustees",
    "Multnomah County, Oreg., commissioner",
    "commissioner, Cook County, Ill., board",
    "director of corrections, city of Jacksonville, Fla., sheriff's office",
    "member of the Whitley County, Ind. Council",
    "county council",
    "deputy supervisor, Orangetown, N.Y.",
    "Hillsborough County, N.H., treasurer",
    "West Miami City Commission",
    "school committee",
    "Murphysboro Township, Ill., trustee",
    "urban planner, Toledo-Lucas County, Ohio, Plan Commissions",
    "Shelby County, Tenn., commissioner",
    "Mayor pro tem, Lakeland, Fla.",
    "commissioner, Lakeland, Fla.",
    "member of the Madison County, Ala., commission",
    "superintendent, Denver Public Schools",
    "Cook County, Ill., chief administrative officer",
    "Sedgwick County, Kans., treasurer",
    (
        "president and chief executive officer of the Salt Lake Organizing Committee"
        " for the Olympic Winter Games of 2002"
    ),
    "Broward County, Fla., commissioner",
    "school district board",
    "commissioner, Mobile County, Ala.",
    "El Paso County, Tex., commissioner",
    "member of the Harris County, Tex., commissioners court",
    "commissioner, San Diego unified port district",
    "member of the Contra Costa County, Calif., board of supervisors",
    "member, San Francisco Board of Supervisors",
    "auditor of Montgomery County, Iowa",
    "member of the Essex County educational services commission",
    "Wood County, Ohio, commissioner",
]

stateLeg = [
    "state house of representatives",
    "state senat",  # to include senator
    "state assembly",
    "Carolina house of representatives",
    "house of delegates",
    "Indiana house of representatives",
    "member of the Indiana general assembly",
    "general assembly",
    "Iowa house of representatives",
    "Florida house of representatives",
]

electedFedOrStateOffice = [
    "state commissioner of agriculture",
    "lieutenant governor",
    "secretary of state",
    "general treasurer",
    "governor of",
    "Pennsylvania auditor general",
    "California state board of equalization",
    "California state insurance commissioner",
    "New Hampshire executive council",
    "Mississippi state commissioner of agriculture and commerce",
    "Montana state auditor",
    "member of the South Dakota public utilities commission, 2004-2011",
    "Missouri state treasurer",
    "Kansas state treasurer",
]

nonElectedGovJob = [
    "staff",
    "chief of staff",
    "aide",
    "housing officer, Wisconsin housing and development authority",
    "executive director, Colorado department of regulatory agencies",
    "California state assembly fellow",
    "executive director, South Carolina state commission for farm workers",
    "director of the Office of Policy Planning, Federal Trade Commission",
    "legislative assistant, New York state assembly",
    "staff for United States Representative",
    "worked for United States Senator",
    "North Carolina Department of Administration",
    "Consumer Financial Protection Bureau",
    "Federal Deposit Insurance Corporation",
    "staff counsel, United States House Select Committee on Assassinations",
    "member, Texas Historical Commission",
    "emergency 9-1-1 dispatcher",
    "Iowa Department of Public Health",
    "senior advisor, United States Department of Health and Human Services",
    "director, Washington state department of revenue",
    "public member, Oregon State Board of Examiners of Nursing Home Administrators",
    "Pennsylvania state secretary of revenue",
    (
        "appointed special assistant to the United States Secretary of Labor by"
        " President George W. Bush"
    ),
    "legislative fellow, Office of Legislative Affairs, United States Navy",
    "member of the Ariz., state board of equalization",
    "state transportation agency employee",
    "analyst, National Nuclear Security Administration",
    "postal inspector, United States Postal Service",
    "special assistant and speechwriter for President William J. Clinton",
    "legal counsel, Illinois State senate judiciary committee 1972-1982",
    "foreign service officer, United States Department of State",
    "Secretary of the Interior in the Cabinet of President Donald J. Trump",
    "White House Fellow and staff member during the George H. W. Bush administration",
    (
        "interim director and deputy director, Inland Empire regional office of the"
        " Governor of California"
    ),
    "Executive Office of the President",
    "counsel to Utah Governor John Huntsman",
    "counsel, U.S. Senate Subcommittee on Alcoholism and Narcotics",
    (
        "Indiana state department of homeland security counterterrorism and counter"
        " intelligence"
    ),
    "Regional Administrator, US Department of Housing and Urban Development",
    "Nebraska Coordinating Commission for Postsecondary Education",
    (
        "Minnesota state director, United States Department of Agriculture Rural"
        " Development"
    ),
    "White House Fellow",
    "United States Ambassador",
    "member of the Texas veterans commission",
    "trustee, New Mexico state natural resources",
    "Tennessee commissioner of agriculture",
    "field director, division of shellfish sanitation, Va., department of health",
    "legislative assistant to Senator Marlow Cook",
    "Wyoming state lands and investment acting director",
    "ordinary seaman, National Oceanic and Atmospheric Administration",
    "special counsel to Louisiana governor Buddy Roemer",
    "White House fellow during the William J. Clinton administration",
    "assistant secretary, United States Department of Veterans' Affairs, 2009-2011",
    "North Dakota state tourism director",
    "member of the California high speed rail authority, 2015-2016",
    (
        "associate administrator and rural administrator, United States Department of"
        " Agriculture"
    ),
    "member, Calif. workforce development board, 2012-2016",
    "director of the Washington state department of agriculture",
    "director of the Florida department of emergency management",
    "economist, United States Environmental Protection Agency",
    "intern, office of the attorney general, Washington, D.C.",
    "member, Indiana state judicial nominating commission",
    "employment counselor, South Carolina state employment security commission",
    "lottery commissioner, state of Michigan",
    (
        "member of the New Hampshire Advisory Committee to the Adequacy in Education"
        " and Finance Commission"
    ),
    "New England regional director, United States Small Business Administration",
    "chair, New York City commission on human rights",
    "member of the N.Mex. public regulation commission",
]
